<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>houtu-dependencies</artifactId>
        <groupId>com.houtu</groupId>
        <version>2.7.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>houtu-web-security</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- Cache2k -->
        <dependency>
            <groupId>org.cache2k</groupId>
            <artifactId>cache2k-api</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.cache2k</groupId>
            <artifactId>cache2k-spring</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- jwt -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.houtu</groupId>
            <artifactId>houtu-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>com.houtu</groupId>
            <artifactId>houtu-web</artifactId>
        </dependency>
    </dependencies>

</project>
